language: java
jdk: openjdk8
notifications:
  slack:
    secure: R5qWppcIwBcWgpZV24XU6aOwSIF/ppSmQdisph79Pb/XXYJHVND+ggovngFRYoa8ilsYxt+jTAvIeryk8Kdvt0vht7FOvNAsoYSZ3qLPg9IyhpFHFsgyRhyQgKd5gQtcAC3jIQ2ACGQWXTW1vlsmgyZqDzueSNPe4Sd9WoWlCPdRV8HuyEyJg2TGnFtjsaki95dE+C++/529R6mRZ1osmDdNgloMPI9yRFEUcuvvkvvCd+kB41h70r/ktg/dYx6mC7WxS67+jhBDFhECFkDYV7HFT9gq+C/eXSnM+oG0xw0ePLHeagAx27BrUsa1cfK1kS3sOGuehK/9oXtUwIixlJ8uNw3bAnlEhIFT890gjxt8vxg68k40bmx4xGbtRWrXkFlD69j33ItfMmCvR22q98P5cUusRMW++Wca+OmbHek2OtKZzRPKmqEDzWszxi5qrOHRbhZv8B/JIYFt++usSgWIbMIABzcCWeCg55zXEWlYryj1UGweUrTDIZvfP4rLetpAehRtIMx9Mfik1wvYEnD4pM4boOgrjZyoUwbvoYFdXDjqJcvDnYxrt20A/fD2JPVB+0+k8zH3MAkqxI9hclwThYOaFDXVLIFBx4QjVeVXx69kAoLVe8H+zdZrxLv4eJ1ZvcuOfMRzPoLluA0i5uhKe6drzIxgZkechJrOGMk=
deploy:
  provider: releases
  api_key:
    secure: M9firbErzvJJmynndD9onkiFDlBGEoqM8hTcRht8OkaLKxJK3up9Ppw9g3Qjmnmy7VXbB5be/jg9J2tJbSFQ00pockb/KHAJc1R5Jl/Aeu+5qJajJpOeTOHDXPll+jUi+6sJV/0d8KSq3PPb2seyYFjb8rCrEj6MECY5CxdyH3Oq/zdEpe2NxZ7wh5JPmeVJ9YHE/EhTMcfaXFxiBO0LrAbXFG+gIMKktUos7GDrtc1CSApp9e8ceLvaBecAXjNavboqwisK2y1aKBpu92jL3STZaC/VbWbfRxM0f8SduSEyHNhJcWRxDPsNPKB/f4IhKCm6z9M//fMC+xdRmTk5mT1X5Kuur61Extb3OAn1VNOSwK2uXX2WEYU5F+fNrdfb2q1S38kAenzgVaHZHnRkhycEBi0sT+lSsaMzF0HJdaXtidjkGTDKaVKBcJImTyYUYDyjRike547AtXD3/M3XRi+lnUu3hOMqf+/A3sFRyaySl+mu9LWf5HInTFcSL/KPsv5VfHu8OsLbxz9FdJnRPhclvOYMQLgyWD/NtJToebmoe6p+ntGuBTorSTY29R7hbE/V4mjNhiuGqTQDeU8PsJgzES+6nqHpkYEmxBmY5+yffKpfhhGuza9TDgKRxXxucXLqokmneA80W8gTPN1+wgUYsBe+wo8g6uEcS29SiiE=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-devops-statistics-plugin
