language: java
jdk: openjdk8
notifications:
  slack:
    secure: R5qWppcIwBcWgpZV24XU6aOwSIF/ppSmQdisph79Pb/XXYJHVND+ggovngFRYoa8ilsYxt+jTAvIeryk8Kdvt0vht7FOvNAsoYSZ3qLPg9IyhpFHFsgyRhyQgKd5gQtcAC3jIQ2ACGQWXTW1vlsmgyZqDzueSNPe4Sd9WoWlCPdRV8HuyEyJg2TGnFtjsaki95dE+C++/529R6mRZ1osmDdNgloMPI9yRFEUcuvvkvvCd+kB41h70r/ktg/dYx6mC7WxS67+jhBDFhECFkDYV7HFT9gq+C/eXSnM+oG0xw0ePLHeagAx27BrUsa1cfK1kS3sOGuehK/9oXtUwIixlJ8uNw3bAnlEhIFT890gjxt8vxg68k40bmx4xGbtRWrXkFlD69j33ItfMmCvR22q98P5cUusRMW++Wca+OmbHek2OtKZzRPKmqEDzWszxi5qrOHRbhZv8B/JIYFt++usSgWIbMIABzcCWeCg55zXEWlYryj1UGweUrTDIZvfP4rLetpAehRtIMx9Mfik1wvYEnD4pM4boOgrjZyoUwbvoYFdXDjqJcvDnYxrt20A/fD2JPVB+0+k8zH3MAkqxI9hclwThYOaFDXVLIFBx4QjVeVXx69kAoLVe8H+zdZrxLv4eJ1ZvcuOfMRzPoLluA0i5uhKe6drzIxgZkechJrOGMk=
deploy:
  provider: releases
  api_key:
    secure: U53DwyBrORr0IVftNY+owt19YdYBRGPIZl/4hElxHqixvGmRTU8grXFKqZlh5Feuvyo663T966NujfkkeZaiBRcpOcaO1IySKwef4WzxHvJQBAGxqTF0gSiEIRCZSN/B3Z5IxlJimjdNTLhby4UNPHy6ZwiKQSregfAjhW1IiX50OmgBRNE6l0xpRMX1U97nTslzbSaypnal0OeX8rYtY0TuAe9lwX9fDZWTYLM3TqmgwNQVGKkGUuOFplaNYOCrbzPLXB2RigibVIpw+Jb05bfueVsWEDWpoUWV4r8DotE+aAZQihnsO9Msm6ToSBk9KFnzslv7d0QuVVs1/7joRjra8jFkNZJQ4YVGEWLaCexr9aMv0YJodmMEF/wzf6BDH7FKfMNeHYLCeGe6smjo+vUBXDgFeMG7VF0SgkDA/WOqg81t5why1NJjpWFseYEogotoM8dBui9qYchvtf7jX42hmDe+hC3Loacc/VLnWjeCIv+osDiAWGgjo9KsNas3yqei6EKsddMwk+1id+ox+/cVnAK5meNWhDHey5AtSv27prrBkJAbWuqcvGunRnFkgqhgF77hR70uN4rdzDS0l90tChkE7XEuRpToHUri8JQ76e4auCWAak9j0/uOTR8szr2zKOFNqz3EXccVgIFAGkz82XV4jm/z8EbaqMLTYgk=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-devops-statistics-plugin
